
baseURL: "/"
languageCode: "en-us"
title: "ExpDev by Diego - Tech Blog"
theme: ["PaperMod"]

taxonomies:
  category: categories
  tag: tags

params:
  env: production
  defaultTheme: auto
  homeInfoParams:
    Title: "Diego Gomes Borges"
    Content: >
      Welcome!!!
      Iâ€™m Diego Gomes Borges, a technology enthusiast and software developer who loves building smart, useful solutions. After a lot of studying, practice, and conversations, I decided to bring everything together in one place.
  assets:
    favicon: "favicon.ico"
    favicon16x16: "favicon-16x16.png"
    favicon32x32: "favicon-32x32.png"
    apple_touch_icon: "apple-touch-icon.png"
    safari_pinned_tab: "safari-pinned-tab.svg"
menus:
  main:
    - name: "Home"
      url: "/"
      weight: 1
    - name: "About"
      url: "/about/"
      weight: 2
    - name: "Posts"
      url: "/posts/"
      weight: 3
