
baseURL: "https://example.com/"
languageCode: "en-us"
title: "Meu Site de TI"
theme: ["PaperMod"]

module:
  imports:
    - path: github.com/adityatelange/hugo-PaperMod

params:
  env: production
  defaultTheme: auto
  homeInfoParams:
    Title: "Ol√°, eu sou o Diego üëã"
    Content: >
      Bem-vindo ao meu site pessoal de TI.
      Aqui compartilho tutoriais, projetos e conte√∫dos t√©cnicos.
